name: Simple Terraform Azure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

# OIDC token + repo read के लिए permissions
permissions:
  id-token: write
  contents: read

# समान ref पर concurrent apply रोकने के लिए
concurrency:
  group: terraform-azure-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform_deploy:
    name: "Terraform Deploy"
    runs-on: self-hosted

    # Terraform AzureRM provider को OIDC use करने के लिए env
    env:
      ARM_USE_OIDC: "true"
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Azure Login (OIDC)"
        # OIDC-based login के लिए v2 use करें
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # public Azure में default audience ठीक है (api://AzureADTokenExchange)
          # audience: api://AzureADTokenExchange

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        id: init
        # backend-config अपने Azure Storage backend के हिसाब से रखें
        run: >
          terraform init -input=false
          -backend-config="resource_group_name=ms-rg"
          -backend-config="storage_account_name=msstg3"
          -backend-config="container_name=tfstate"
          -backend-config="key=terraform.tfstate"

      - name: "Terraform State Pull"
        # backend कनेक्शन validate करने में मदद
        run: terraform state pull

      - name: "Terraform Plan"
        id: plan
        # predictable output के लिए flags
        run: terraform plan -input=false -no-color -out=tfplan

      - name: "Terraform Show"
        # human-readable plan देखें
        run: terraform show -no-color tfplan

      - name: "Terraform Apply"
        id: apply
        # non-interactive apply
        run: terraform apply -input=false -auto-approve
